### PR TITLE
feat: prevent caching of python-input-sw.js

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Ref: https://github.com/freeCodeCamp/freeCodeCamp/issues/52536 

For context, I didn't want to clash with Gatsby's sw.js (in principle it shouldn't, but I didn't want to risk it), so I created a new service worker file to handle input and cancellation requests for the python worker. Ref: https://github.com/freeCodeCamp/freeCodeCamp/pull/52526 and https://github.com/freeCodeCamp/freeCodeCamp/pull/52587

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@raisedadead I'm a bit out of the loop re: how/if we still use this. Assuming we do, this is the change I would like.

**Review by ShaunSHamilton — APPROVED** [review]
I did not test, but this looks like what I expect to work.

**Comment by ojeytonwilliams** [comment]
I confirmed it worked locally (built the site and checked the headers). I'm just not sure about deployment.

**Comment by raisedadead** [comment]
So this has to be updated in all the client instances once this is merged. Do we have a date for the deployment?

**Comment by ShaunSHamilton** [comment]
> Do we have a date for the deployment?

Yes, the articles are set to go out early on the 20th of December. So, we should have prod out by/before then

**Pull request merged**
